# Site settings
title: The Philippines
description: >
  A resplendent collection of over 7,000 island paradises, where clear shallow waters lap endless sand banks and hidden coves – a treat for explorers and deck-chair loungers alike.
baseurl: "/philippines" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
